version: "3.8"

services:
  product_service:
    build:
      context: .
      dockerfile: "Dockerfile.api"
    env_file:
      - .env
    ports:
      - "8000:8000"


  product_service_database:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - postgres_data:/data/db
    ports:
      - "5432:5432"

networks:
  cloud_dev_internal_net:
    driver: bridge

volumes:
  postgres_data:
      driver: local
