FROM python:3.10-buster

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY app .

CMD [ "python", "product_service_server.py" ]