# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\x11\n\x03PID\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x05PInfo\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32<\n\x0eProductService\x12*\n\nGetProduct\x12\x0c.product.PID\x1a\x0e.product.PInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PID._serialized_start=26
  _PID._serialized_end=43
  _PINFO._serialized_start=45
  _PINFO._serialized_end=82
  _PRODUCTSERVICE._serialized_start=84
  _PRODUCTSERVICE._serialized_end=144
# @@protoc_insertion_point(module_scope)
